[features]
seeds = false
skip-lint = false

[programs.localnet]
alpha_pack_core = "AlphaPackCoreProgram111111111111111111111"

[programs.devnet]
alpha_pack_core = "AlphaPackCoreProgram111111111111111111111"

[programs.mainnet]
alpha_pack_core = "AlphaPackCoreProgram111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/alpha-pack-core",
    "programs/pack-manager", 
    "programs/competition-engine",
    "programs/arbitrage-executor",
    "programs/social-rewards",
    "programs/cross-chain-bridge"
]

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "AlphaPackCoreProgram111111111111111111111"
program = "target/deploy/alpha_pack_core.so"

[test.validator]
url = "https://api.devnet.solana.com"
clone = [
    { address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA", filename = "spl_token.so" },
    { address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL", filename = "spl_associated_token.so" },
    { address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s", filename = "mpl_token_metadata.so" }
]

[test.validator.account]
address = "SysvarRent111111111111111111111111111111111"
filename = "rent.json"
