global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Alpha Pack API
  - job_name: 'alphapack-api'
    static_configs:
      - targets: ['api:3001']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 30s

  # Alpha Pack Frontend
  - job_name: 'alphapack-frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  # Trading Engine
  - job_name: 'trading-engine'
    static_configs:
      - targets: ['trading-engine:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Social Engine
  - job_name: 'social-engine'
    static_configs:
      - targets: ['social-engine:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Node Exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Solana Validator (local dev)
  - job_name: 'solana-validator'
    static_configs:
      - targets: ['solana-validator:8899']
    metrics_path: '/metrics'
    scrape_interval: 60s

  # ML Model Server
  - job_name: 'ml-server'
    static_configs:
      - targets: ['ml-server:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

# Recording rules for Alpha Pack metrics
recording_rules:
  - name: alphapack.rules
    rules:
      # Trading metrics
      - record: alphapack:trading_volume_total
        expr: sum(rate(alphapack_trades_total[5m])) by (pack_id)
      
      - record: alphapack:trading_success_rate
        expr: |
          sum(rate(alphapack_trades_successful_total[5m])) by (pack_id) /
          sum(rate(alphapack_trades_total[5m])) by (pack_id)
      
      - record: alphapack:arbitrage_opportunities_per_minute
        expr: rate(alphapack_arbitrage_opportunities_total[1m])
      
      # Social metrics
      - record: alphapack:viral_content_rate
        expr: |
          sum(rate(alphapack_content_viral_total[5m])) by (pack_id) /
          sum(rate(alphapack_content_total[5m])) by (pack_id)
      
      - record: alphapack:social_engagement_score
        expr: sum(alphapack_social_engagement_total) by (pack_id, platform)
      
      # Pack metrics
      - record: alphapack:pack_performance_score
        expr: |
          (
            alphapack:trading_success_rate * 0.4 +
            alphapack:viral_content_rate * 0.3 +
            alphapack:social_engagement_score / 1000 * 0.3
          )
      
      # System metrics
      - record: alphapack:api_request_rate
        expr: sum(rate(http_requests_total[5m])) by (method, endpoint)
      
      - record: alphapack:api_error_rate
        expr: |
          sum(rate(http_requests_total{status=~"5.."}[5m])) by (method, endpoint) /
          sum(rate(http_requests_total[5m])) by (method, endpoint)

# Alerting rules
alerting_rules:
  - name: alphapack.alerts
    rules:
      # High error rate
      - alert: HighErrorRate
        expr: alphapack:api_error_rate > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.endpoint }}"
      
      # Low trading volume
      - alert: LowTradingVolume
        expr: alphapack:trading_volume_total < 100
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Low trading volume detected"
          description: "Trading volume is below threshold for pack {{ $labels.pack_id }}"
      
      # Database connection issues
      - alert: DatabaseDown
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Database is down"
          description: "PostgreSQL database is not responding"
      
      # Redis connection issues
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "Redis cache is not responding"
      
      # High memory usage
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 90%"
      
      # High CPU usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is above 80%"
      
      # Disk space low
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Disk space low"
          description: "Disk space is below 10% on {{ $labels.mountpoint }}"
      
      # ML model inference slow
      - alert: SlowMLInference
        expr: histogram_quantile(0.95, rate(ml_inference_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "ML inference is slow"
          description: "95th percentile inference time is {{ $value }}s"
      
      # Arbitrage opportunities missed
      - alert: MissedArbitrageOpportunities
        expr: increase(alphapack_arbitrage_opportunities_missed_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Missing arbitrage opportunities"
          description: "{{ $value }} arbitrage opportunities missed in the last 5 minutes"
